name: Build QGC MacOS 

#We only perform this on the "main" branch
on: 
    push:
        branches:
        - actions-build-macOS-test4

defaults:
  run:
    shell: bash

env:
  JOBS: 4
  SPEC: macx-clang
  CONFIG: installer
  ACTIONS_BUILD_DIR: ${{ github.workspace }}/../qgroundcontrol
  SHADOW_BUILD_DIR: /tmp/shadow_build_dir



jobs:
  #Name of the jod in this case "build"
  build-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        exclude:
          - os: ubuntu-latest
          - os: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Add wget package
        run: brew install  wget

      - name: Before install
        run:  cd ${ACTIONS_BUILD_DIR} && git fetch --unshallow && git fetch --all --tags;
              export JOBS=$((`sysctl -n hw.ncpu`+1));

      - name: install osx dependencies 1
        #if:   ${{SPEC}}" == "macx-clang"
        run:  wget --quiet https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/Qt5.12.6-clang_64-min.tar.bz2 &&
              tar -jxf Qt5.12.6-clang_64-min.tar.bz2 -C /tmp &&
              wget --quiet https://qgroundcontrol.s3-us-west-2.amazonaws.com/dependencies/gstreamer-osx-1.18.1.tar.bz2 &&
              sudo tar -zxf gstreamer-osx-1.18.1.tar.bz2 -C /Library/Frameworks &&
              export QT_DIR=Qt5.12-clang_64/5.12.6/clang_64 &&
              export QT_QPA_PLATFORM_PLUGIN_PATH=/tmp/$QT_DIR/plugins &&
              export QML2_IMPORT_PATH=/tmp/$QT_DIR/qml &&
              export PATH=/tmp/$QT_DIR/bin:$PATH

        
      - name: create qmake
        #if:   ${{SPEC}}" == "macx-clang"
        run:  mkdir ${SHADOW_BUILD_DIR} && cd ${SHADOW_BUILD_DIR} &&
              qmake -r ${ACTIONS_BUILD_DIR}/qgroundcontrol.pro &&
              xcodebuild -IDEBuildOperationMaxNumberOfConcurrentCompileTasks=$JOBS -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c && $(exit ${PIPESTATUS[0]})